/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ma.fstm.ilisi.projectbusway.presentation;


import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static ma.fstm.ilisi.projectbusway.controleur.Busway.arretvoyage1;
import ma.fstm.ilisi.projectbusway.metier.bo.Arret;
import ma.fstm.ilisi.projectbusway.metier.bo.Bus;
import ma.fstm.ilisi.projectbusway.metier.bo.Conduire;
import ma.fstm.ilisi.projectbusway.metier.bo.Voyage;
/**
 *
 * @author Aya
 */
public class BusInformation extends javax.swing.JFrame {

    /**
     * Creates new form BusInformation
     */
    public BusInformation() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	// Arret.CreerArrets(); 
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Chercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        

        jLabel1.setText("Numero Bus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton1)))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private JPanel createBusPanel(Bus bus) 
    {
       // JPanel panel = new JPanel(new GridLayout(0, 6));
        JPanel panel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        int numeroBus = bus.getNumeroBus();
        int nombreLimite = bus.getNumeroPlacesLimite();
        int nombreReservation = bus.getNumeroPlacesLimite() - bus.getNumeroPlacesLibres();

       JButton voirVoyages = new JButton("Voir Voyages");
        voirVoyages.addActionListener(e -> {
            Arret arretInstance = new Arret();
            arretInstance.CreerArrets();
            for (Voyage v : bus.getLesVoyages()) {
                StringBuilder infoVoyage = new StringBuilder();
                for (Arret arret : arretvoyage1(v)) {
                    System.out.println(arret.getStation().getNomStation());
                    infoVoyage.append("Nom station :").append(arret.getStation().getNomStation()).append(" heure arret :").append(arret.getHeureArret()).append("\n");
}
               JOptionPane.showMessageDialog(null, "id :" + v.getIdVoyage() + "\nDate depart :" + v.getDateDepart() + "\nDate arrive :" + v.getDateArrivee()+ "\nLes arret :\n"+infoVoyage, "Voyage", JOptionPane.INFORMATION_MESSAGE);
            }
        });

        JButton voirConducteur = new JButton("Voir Conducteur");
        voirConducteur.addActionListener(e -> {
            new Conduire();
            for (Conduire cd : Conduire.cond) {
                if (cd.getLesBus().getIdBus() == bus.getIdBus()) {
                   String nomEtMatricule = "Nom: " + cd.getLesChauffeurs().getNomConducteur() + "\nMatricule: " + cd.getLesChauffeurs().getIdConducteur();
JOptionPane.showMessageDialog(null, nomEtMatricule, "Noms et matricules des conducteurs", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }
            
        });

        panel.add(new JLabel("Numéro Bus: " + numeroBus), gbc);
        gbc.gridx =  gbc.gridx + 5;
        panel.add(new JLabel("      Nombre Limite: " + nombreLimite), gbc);
        gbc.gridx =  gbc.gridx + 5;
        panel.add(new JLabel("      Nombre Réservation: " + nombreReservation), gbc);
        gbc.gridx =  gbc.gridx + 5;
        panel.add(voirVoyages, gbc);
        gbc.gridx =  gbc.gridx + 5;
        panel.add(voirConducteur, gbc);
        return panel;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:      
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
        if (jTextField1.getText().isEmpty()) 
        {
            for (Bus bus : Bus.getTousLesBus()) 
            {
                System.out.println("Creating panel for bus: " + bus.getIdBus());
                JPanel panel = createBusPanel(bus);
                mainPanel.add(panel);
                this.setContentPane(mainPanel);
                this.revalidate();
                this.repaint();
            }
           
        }
        else 
        {
            int busNum = Integer.parseInt(jTextField1.getText());
            Bus bus = Bus.ChercherBusparNumero(busNum);
            if (bus != null) 
            {
                System.out.println("Creating panel for bus: " + bus.getIdBus());
                JPanel panel = createBusPanel(bus);
                mainPanel.add(panel);
                this.setContentPane(mainPanel);
                this.revalidate();
                this.repaint();
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Aucun Bus disponible pour ce numero!\n Essaye d'afficher tous les bus en cliquant sur chercher", "Attention", JOptionPane.WARNING_MESSAGE);
            }    
        }  

    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
