/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ma.fstm.ilisi.projectbusway.presentation;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import ma.fstm.ilisi.projectbusway.metier.bo.Arret;
import ma.fstm.ilisi.projectbusway.metier.bo.Reservation;
import ma.fstm.ilisi.projectbusway.metier.bo.Voyage;
import ma.fstm.ilisi.projectbusway.metier.dao.ReservationDAO;
/**
 *
 * @author DELL
 */
public class infoBusVoyage extends javax.swing.JFrame {

    /**
     * Creates new form infoBusVoyage
     */
	private int a=5;
    public infoBusVoyage() {
        //initComponents();
    }
        public infoBusVoyage(Voyage voyage) {
        initComponents1(voyage);
       //System.out.println("Depart : " + v.getLeDepart().getNomStation());
       jTextFieldDepart.setText(voyage.getLeDepart().getNomStation() );
       jTextFieldArrivee.setText(voyage.getlArrivee().getNomStation() );

    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
       
    private void initComponents1(Voyage voyage) {

    jScrollPane2 = new javax.swing.JScrollPane();
    jTable2 = new javax.swing.JTable();
    jTextField1 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList<>();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jTextFieldDepart = new javax.swing.JTextField();
    jTextFieldArrivee = new javax.swing.JTextField();
    Arret arretInstance = new Arret();
   // arretInstance.CreerArrets(); // Assurez-vous que la méthode CreerArrets() est accessible
    List<Arret> listeArrets = new ArrayList() ;
    System.out.println("the probleme is here");
    for (Arret vararr : Arret.lesarrets)
    {
    	 
                     listeArrets.add(vararr);
    }
//    
//    for (Arret a : listeArrets)
//    {
//    	 System.out.println("id voyage : "+a.getVoyage().getIdVoyage() + " id station " + a.getStation().getIdStation());
//    	 
//    }


    System.out.println(listeArrets);
    
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {
            "Id reservation", "Date reservation", "CIN de passage", "Nom prenom"
        }
    ));
    
    jScrollPane2.setViewportView(jTable2);

    jTextField1.addActionListener(new java.awt.event.ActionListener() 
    {
        public void actionPerformed(java.awt.event.ActionEvent evt) 
        {
            jTextField1ActionPerformed(evt);
        }
    });

    jButton1.setText("Chercher");
    jButton1.addActionListener(new java.awt.event.ActionListener() 
    {
        public void actionPerformed(java.awt.event.ActionEvent evt) 
        {
            jButton1ActionPerformed(evt);
        }
    });

    jLabel1.setText("CIN:");

   jList1.setModel(new javax.swing.AbstractListModel<String>() {
    // Implémenter la méthode getValue() pour obtenir les éléments de la liste

@Override
public String getElementAt(int index) {
    // Déclaration et initialisation de la liste temporaire pour stocker les chaînes
    List<String> stringList = null;

   
    // Vérifie si la liste des arrêts n'est pas nulle
    if (listeArrets != null && !listeArrets.isEmpty()) {
    	 stringList = new ArrayList<>();
        // Parcourir la liste des arrêts
    	System.out.println("voyage id " +voyage.getIdVoyage());
    	
        for (Arret a : listeArrets) {
            // Vérifier si l'arrêt appartient au voyage actuel
        	
            if (a.getVoyage().getIdVoyage() == voyage.getIdVoyage()) {
                // Ajouter le nom de la station à la liste des chaînes
                stringList.add(a.getStation().getNomStation());
                System.out.println("id voyage : "+a.getVoyage().getIdVoyage() + " id station " + a.getStation().getIdStation());
            }
        }
    }
    
    if (!stringList.isEmpty()) {
        stringList.remove(0);
    }

    // Supprimer le dernier élément de la liste
    if (!stringList.isEmpty()) {
        stringList.remove(stringList.size() - 1);
    }
    
    // Convertir la liste en tableau
    String[] strings = stringList.toArray(new String[0]);
   
    System.out.println("tableau : ");
    for(String s:strings)
    {
    	 System.out.println(s);
    }
    
   
    
    
    // Vérifier si l'index est valide
    if (index >= 0 && index < strings.length) {
        // Retourner l'élément à l'index spécifié
        return strings[index];
    } else {
        // Gérer le cas où l'index est invalide
        return null; // Ou une autre valeur par défaut selon vos besoins
    }
    
}


    // Implémenter la méthode getSize() pour obtenir la taille de la liste
    @Override
    public int getSize() {
        return 10; // Retourner la taille de la liste
    }
});

    jScrollPane1.setViewportView(jList1);
     SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    jLabel2.setText("Liste des reservations");

    jLabel3.setText("Départ :");

    jLabel4.setText("Arrivée :");

    jTextFieldDepart.setEditable(false);
    jTextFieldDepart.setText(voyage.getLeDepart().getNomStation() + " " + voyage.getDateDepart().toString());
    jTextFieldDepart.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldDepartActionPerformed(evt);
        }
    });
    


    jTextFieldArrivee.setEditable(false);
    jTextFieldArrivee.setText(voyage.getlArrivee().getNomStation() + " " + voyage.getDateArrivee().toString());

     //new Voyage().CreerVoyages(); 
     List<Reservation> rs= new ReservationDAO().getPassagersReserves(voyage.getBus().getIdBus());
     voyage.setLesReservations(rs);
    List<Reservation> reservations = voyage.getLesReservations();  
    if (reservations != null && !reservations.isEmpty()) 
    {
    	System.out.println("heeeeeeeeeeeeeere");
        for (Reservation reservation : reservations) 
        {
                System.out.println("size est " + reservations.size());
                System.out.println("id est " + reservation.getIdReservation());
                ((DefaultTableModel) jTable2.getModel()).addRow(new Object[]{reservation.getIdReservation(), 
                reservation.getHeureReservation(), 
                reservation.getPassager().getCIN(), 
                reservation.getPassager().getNomPassager()});
        }
}

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)) // Réglage de la largeur de la JList
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(20, Short.MAX_VALUE))
);
layout.setVerticalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
);


    pack();
}
    
        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        jScrollPane2 = new javax.swing.JScrollPane();
//        jTable2 = new javax.swing.JTable();
//        jTextField1 = new javax.swing.JTextField();
//        jButton1 = new javax.swing.JButton();
//        jLabel1 = new javax.swing.JLabel();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jList1 = new javax.swing.JList<>();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        jTextFieldDepart = new javax.swing.JTextField();
//        jTextFieldArrivee = new javax.swing.JTextField();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jTable2.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null, null},
//                {null, null, null, null, null},
//                {null, null, null, null, null},
//                {null, null, null, null, null},
//                {null, null, null, null, null}
//            },
//            new String [] {
//                "Id reservation", "date reservation", "heure reservation", "cin de passage", "nom prenom"
//            }
//        ) {
//            boolean[] canEdit = new boolean [] {
//                false, false, false, false, true
//            };
//
//            public boolean isCellEditable(int rowIndex, int columnIndex) {
//                return canEdit [columnIndex];
//            }
//        });
//        jScrollPane2.setViewportView(jTable2);
//
//        jTextField1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField1ActionPerformed(evt);
//            }
//        });
//
//        jButton1.setText("chercher");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jLabel1.setText("cin");
//
//        jList1.setModel(new javax.swing.AbstractListModel<String>() {
//            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
//            public int getSize() { return strings.length; }
//            public String getElementAt(int i) { return strings[i]; }
//        });
//        jScrollPane1.setViewportView(jList1);
//
//        jLabel2.setText("Liste des station de voyage avec heure");
//
//        jLabel3.setText("Depart :");
//
//        jLabel4.setText("Arrivee :");
//
//        jTextFieldDepart.setEditable(false);
//        jTextFieldDepart.setText("Station 1 15:00");
//        jTextFieldDepart.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextFieldDepartActionPerformed(evt);
//            }
//        });
//
//        jTextFieldArrivee.setEditable(false);
//        jTextFieldArrivee.setText("Station 5 19 :00");
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(25, 25, 25)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel4)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addComponent(jTextFieldArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jLabel1)
//                                .addGap(18, 18, 18)
//                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(jButton1)
//                                .addGap(61, 61, 61))
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel3)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addComponent(jTextFieldDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(254, 254, 254))))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(14, 14, 14)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addComponent(jLabel2)
//                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(6, 6, 6)))
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(43, 43, 43))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addGap(24, 24, 24)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addGap(33, 33, 33)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(jLabel3)
//                                    .addComponent(jTextFieldDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(23, 23, 23)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(jLabel4)
//                                    .addComponent(jTextFieldArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel2)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                    .addComponent(jButton1)
//                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                    .addComponent(jLabel1))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
//                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(0, 0, Short.MAX_VALUE)))
//                .addGap(41, 41, 41))
//        );
//
//        pack();
//    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextFieldDepartActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoBusVoyage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoBusVoyage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoBusVoyage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoBusVoyage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoBusVoyage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldArrivee;
    private javax.swing.JTextField jTextFieldDepart;
    // End of variables declaration                   
}
