/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ma.fstm.ilisi.projectbusway.presentation;

import java.awt.Component;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import ma.fstm.ilisi.projectbusway.metier.bo.Bus;
import ma.fstm.ilisi.projectbusway.metier.bo.Conducteur;
import ma.fstm.ilisi.projectbusway.metier.bo.Conduire;
import ma.fstm.ilisi.projectbusway.metier.bo.Voyage;

/**
 *
 * @author Aya
 */
public class InfoBus extends javax.swing.JFrame {

    /**
     * Creates new form InfoBus
     */
    public InfoBus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bus id");

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setText("chercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            	
            	
            },
            new String [] {
                "IdBus", "NumeroBus", "NombrePlacesLimites", "NombreReservation", "Voir Voyages", "Voir Conducteur"
            }
        ));
        jTable2.setColumnSelectionAllowed(true);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel6.setBackground(new java.awt.Color(255, 153, 255));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField4.setText("Info BUS");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        
        
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    // TableCellRenderer pour les boutons
        TableCellRenderer buttonRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                if (value instanceof Component) {
                    return (Component) value;
                } else {
                    // Créez un nouveau JButton vide si la valeur est null
                    return new JButton();
                }
            }
        };

        // TableCellEditor pour les boutons
        TableCellEditor buttonEditor = new DefaultCellEditor(new JCheckBox()) {
            @Override
            public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
                return (Component) value;
            }

            @Override
            public Object getCellEditorValue() {
                return null;
            }

            @Override
            public boolean stopCellEditing() {
                Component comp = getComponent();
                if (comp instanceof JButton) {
                    JButton button = (JButton) comp;
                    button.doClick();
                }
                return super.stopCellEditing();
            }
        };

        // Récupération du modèle de la table
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

        // Nettoyage du modèle de la table
        while (model.getRowCount() > 0)
            model.removeRow(0);

        // Remplissage du modèle avec les données des bus
        if (jTextField1.getText().isEmpty()) {
            for (Bus bus : Bus.getTousLesBus()) {
                int idBus = bus.getIdBus();
                int numeroBus = bus.getNumeroBus();
                int nombreLimite = bus.getNumeroPlacesLimite();
                int nombreReservation = bus.getNumeroPlacesLimite() - bus.getNumeroPlacesLibres();
                JButton voirVoyages = new JButton("Voir Voyages");
                voirVoyages.addActionListener(e -> {
                           
                            
                for (Voyage v :bus.getLesVoyages() )
                {                                   
                    JOptionPane.showMessageDialog(null, "id :"+v.getIdVoyage()+"\nDate depart :"+v.getDateArrivee()+"\nDate arrive :"+v.getDateArrivee(), "Voyage", JOptionPane.INFORMATION_MESSAGE);
                }
                });

                JButton voirConducteur = new JButton("Voir Conducteur");
                voirConducteur.addActionListener(e -> {
                   // System.out.println("conduct" + bus.getIdBus());
                    new Conduire();
                    for(Conduire cd: Conduire.cond)
                    {
                        //System.out.println(cd.getLesBus().getIdBus());
                        if(cd.getLesBus().getIdBus()==bus.getIdBus())
                        {
                            JOptionPane.showMessageDialog(null, cd.getLesChauffeurs().getNomConducteur(), "Noms des conducteurs", JOptionPane.INFORMATION_MESSAGE);
                        break;
                        }
                    }
                    
                });

                // Ajout des données du bus avec les boutons au modèle de la table
                model.addRow(new Object[]{idBus, numeroBus, nombreLimite, nombreReservation, voirVoyages, voirConducteur});
            }
        } else {
            int busId = Integer.parseInt(jTextField1.getText());
            Bus bus = Bus.ChercherBusparId(busId);
            if (bus != null) {
                int idBus = bus.getIdBus();
                int numeroBus = bus.getNumeroBus();
                int nombreLimite = bus.getNumeroPlacesLimite();
                int nombreReservation = bus.getNumeroPlacesLibres();

                JButton voirVoyages = new JButton("Voir Voyages");
                voirVoyages.addActionListener(e -> {
               for (Voyage v :bus.getLesVoyages() )
                {
              //System.out.println("id :"+v.getIdVoyage()+"date depart :"+v.getDateArrivee()+"date arrive :"+v.getDateArrivee());
                
            JOptionPane.showMessageDialog(null, "id :"+v.getIdVoyage()+"date depart :"+v.getDateArrivee()+"date arrive :"+v.getDateArrivee(), "Noms des conducteurs", JOptionPane.INFORMATION_MESSAGE);
                        break;                 
                }
                });

                JButton voirConducteur = new JButton("Voir Conducteur");
                voirConducteur.addActionListener(e -> {
                    for(Conduire cd: Conduire.cond)
                    {
                         System.out.println(cd.getLesBus().getIdBus());
                        if(cd.getLesBus().getIdBus()==bus.getIdBus())
                        {
                            JOptionPane.showMessageDialog(null, cd.getLesChauffeurs().getNomConducteur(), "Noms des conducteurs", JOptionPane.INFORMATION_MESSAGE);
                        break;
                        }
                    }
                });

                // Ajout des données du bus avec les boutons au modèle de la table
                model.addRow(new Object[]{idBus, numeroBus, nombreLimite, nombreReservation, voirVoyages, voirConducteur});
            } else {
                JOptionPane.showMessageDialog(null, "Aucun Bus disponible avec cet ID!", "Attention", JOptionPane.WARNING_MESSAGE);
            }
        }
        jTable2.getColumn("Voir Voyages").setCellRenderer(buttonRenderer);
        jTable2.getColumn("Voir Voyages").setCellEditor(buttonEditor);
        jTable2.getColumn("Voir Conducteur").setCellRenderer(buttonRenderer);
        jTable2.getColumn("Voir Conducteur").setCellEditor(buttonEditor);
    }                                        

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration                   
}
