/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ma.fstm.ilisi.projectbusway.presentation;


import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import ma.fstm.ilisi.projectbusway.controleur.Busway;
import static ma.fstm.ilisi.projectbusway.controleur.Busway.arretvoyage1;
import ma.fstm.ilisi.projectbusway.metier.bo.Arret;
import ma.fstm.ilisi.projectbusway.metier.bo.Station;
import ma.fstm.ilisi.projectbusway.metier.bo.Voyage;

/**
 *
 * @author Aya
 */
public class Reserver extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    public String from;
    public List <Voyage> voyagesp;
    private void mettreAJourHeure() {
        LocalTime heureActuelle = LocalTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        String heureFormatee = heureActuelle.format(formatter);
        jLabel1.setText( heureFormatee);
    }
    
    public Reserver() {
      
                Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mettreAJourHeure();
            }
        });
        timer.start();
        try {
            from = Busway.trouverPlusProche();
        } catch (Exception ex) {
            Logger.getLogger(Reserver.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();

    }
    
    public static String generateTextForScrollPane(List<Voyage> voyagesp) 
    {
    StringBuilder textBuilder = new StringBuilder();
    int l = 1;
    for (Voyage v : voyagesp) 
    {
        textBuilder.append("Ligne ").append(l).append(" : ");
        StringBuilder infoVoyage = new StringBuilder();
        for (Arret arret : arretvoyage1(v)) 
        	
        {
            System.out.println("teeeeeeest il y a arret");
            infoVoyage.append(" -->").append(arret.getStation().getNomStation());
        }
        textBuilder.append(infoVoyage).append("\n");
        l++;
    }
    return textBuilder.toString();
}

     private void writeTextToScrollPane(String text) {
    // Création d'un JLabel avec le texte fourni, en utilisant des balises HTML pour les sauts de ligne
    JLabel label = new JLabel("<html>" + text.replaceAll("\n", "<br>") + "</html>");
    
    // Ajout du JLabel au JScrollPane
    jScrollPane1.setViewportView(label);
    
    // Forcer le JScrollPane à afficher la position 0,0 (en haut à gauche) pour le nouvel élément
    jScrollPane1.getViewport().setViewPosition(label.getLocation());
}
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabel2.setText("Entrer votre CIN");

        jButton1.setText("Reserver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Entrer votre Nom");

       // jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("La ligne reserve");

        jLabel4.setText("Les lignes :");
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(  getAllStationNames().toArray(new String[0]) ));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(24, 24, 24)))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(56, 56, 56)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>                        

   private List<String> getAllStationNames() 
    {      
	//from ="Al Qods";
        Station dep = Busway.trouverStation(from);
        System.out.print("appeeeeeeeeeeeeeeeeeeeeeeeel");
        voyagesp=Busway.trouverVoyageLigne(dep);
        System.out.print("fiin");
        String textForScrollPane = generateTextForScrollPane(voyagesp);
        writeTextToScrollPane(textForScrollPane);
        int i=1;
        List<String> stationNames = new ArrayList<>();
        for(Voyage v: voyagesp)
        {
            System.out.println(v.getIdVoyage());
            stationNames.add("Ligne "+i);
            i++;
        }
        return stationNames;
}
    
   private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
       String selectedStation = (String) jComboBox1.getSelectedItem();
       System.out.println("Station sélectionnée : " + selectedStation);
   }  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String ligne = (String) jComboBox1.getSelectedItem();
            // Supprimer la partie "Ligne " de la chaîne
        String nombreStr = ligne.substring(6);
        
        // Convertir la chaîne représentant le nombre en un entier
        int nombre = Integer.parseInt(nombreStr);
        
        System.out.println("Le nombre extrait de la chaîne est : " + nombre);
    
            Station dep = Busway.trouverStation(from);
            //System.out.println(from);
            Voyage v=voyagesp.get(nombre-1);
            if(v != null)
            {
                LocalTime heureActuelle = LocalTime.now();
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
                    String heureReservation = heureActuelle.format(formatter);
                int option = JOptionPane.showOptionDialog(
                    null,
                    "Vous voulez reserver le voyage suivant:\n Station de départ: " + dep.getNomStation() + "\nHeure de réservation: " + heureReservation,
                    "Confirmation de la réservation",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    null,
                    null
                );
                if (option == JOptionPane.OK_OPTION) 
                {
                    String qrCodeContent = "Station de départ: " + dep.getNomStation() + "\nHeure de réservation: " + heureReservation;
                    BufferedImage qrCodeImage = Busway.generateQRCode(qrCodeContent);
                    JFrame frame = new JFrame("Scannez votre ticket");
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    JLabel label = new JLabel(new ImageIcon(qrCodeImage.getScaledInstance(300, 300, Image.SCALE_SMOOTH)));
                    frame.getContentPane().add(label);
                    frame.pack();
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);        
                  //new
                  boolean find = Busway.reserver(v,jTextField1.getText(),jTextField2.getText(),dep);
                  System.out.println(find);
                }                 
                else
                {                     
                    JOptionPane.showMessageDialog(null, "Réservation annulée", "Annulation", JOptionPane.WARNING_MESSAGE);
                } 
        }
        else 
            {
                JOptionPane.showMessageDialog(null, "Aucun Voyage disponible d'ici une heure!","Attention",0);  
            }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration                   
}
